### ISSUE TITLE
Expose sensor data to ROS

### ISSUE THREAD

**Issue by NikolausDemmel** [MobileRobots/ros-arnl#1]
It would be great to expose the sensor data to ROS with the ros-arnl node. Something like a combination of ros-arnl and rosaria in one node.

Has there been any activity in that direction?

**Comment by reed-adept** [comment]
Haven't thought about it yet, but it could be useful for visualization especially?  

I am planning to add laser data publishing to rosaria, then I may either copy that as is to rosarnl or refactor rosarnl and rosaria to share code (then all topics from rosaria would be available in rosarnl).

However, I am also considering replacing the current rosarnl node (which links directly to ARIA and ARNL libraries) with a separate bridge node that communicates with the "native" arnlServer from ARNL, which would allow people to upgrade or customize arnlServer.  So not sure yet on the direction of ros-arnl, any feedback is appreciated.

**Comment by NikolausDemmel** [comment]
Thanks for you reply and willingness to consider our use-case.

Visualization is one point, sure. However more important for us is the use case of using the Pioneer as a sensor data acquisition platform. We want to rely on a stable localization and navigation solution (ARNL) with nice interface including scheduling of routes to assist us in recording data for specific scenarios/motions/time-of-days etc. We mainly to record data of additional sensors mounted on top of the Pioneer, but we would also like to augment this data with additional information like the ARNL localization pose, the odometry, the US data and raw laser data.

At the moment we are using a modified arnl server were we through in some bits of rosaria to output the localization pose to ROS and accept cmd_vel from ROS (for teleoperation). This was hacked up in a few hours and is by no means something worth sharing.

The "new architecture" for rosarnl that you describe makes sense to me in terms of modularity and flexibility for various use-cases, as long as it allows the implementation of the features described above. One minor concern is what this would mean in terms of performance. I.e. would splitting ros-arnl up into the arnl server and a ros-arnl "client" introduce (significant) additional delay? In our case we consider the ROS interface the primary focus, and the ArNetworking interface is more of a nice-to-have for introspection and control through MobileEyes.

**Comment by reed-adept** [comment]
See https://github.com/amor-ros-pkg/rosaria/issues/34 for similar request for rosaria.

**Comment by reed-adept** [comment]
I just added this, see commit 18fa2da. Let me know if this looks useful.

**Comment by NikolausDemmel** [comment]
Looks good! I haven't had a chance to test it yet, but I like that we get the internal timestamp and not just `now`.

**Comment by reed-adept** [comment]
opened issue #15 specifically for pose data. closing this. any other specific data to publish?

**Comment by NikolausDemmel** [comment]
> any other specific data to publish?

Well, in general anything that the device offers, but laser and odometry are the relevant ones in my use case. Thanks.
