### ISSUE TITLE
fix laser angle increment value in published laser scan topic 

### ISSUE THREAD

**Issue by reed-adept** [MobileRobots/ros-arnl#11]

**Comment by RobertBlakeAnderson** [comment]
Using a PioneerLX, we see that angle_increment is always 0, so ROS thinks all the data are at the minimum angle.

After looking into this, I've found that:
1. LaserPublisher.cpp sets angle_increment at Line 51:
   laserscan.angle_increment = ArMath::degToRad(laser->getIncrement());
2. In the robot parameter file pioneer-lx.p, LaserIncrement is left blank, so it reverts to the default value.
3. LaserIncrement does not appear in default-arnl.p.

So I think the increment simply isn't getting set. I tried giving it a value in pioneer-lx.p, but that introduced a new warning when starting Arnl:
[ WARN] ARNL: S3Series_1: setIncrement: Cannot set increment on this laser

**Comment by reed-adept** [comment]
ARIA has two methods for configuring laser angle increment.  One is to select from a set of choices provided by the laser driver, since most laser sensors have a small set of angle increments they are capable of.  The other is to set it to any arbitrary value.  Looking at the S300/S3000 driver in ARIA (ArS3Series), it appears to use the first method to set the default inceremnt choice to "half" and doesn't implement or use the second method.  So maybe it could use getIncrementChoiceDouble()  (which ought to return 0.5) ...  or this:

```
double inc = 0;  
if(laser->canSetIncrement())
  inc = laser->getIncrement();
else if(laser->getIncrementChoice() != NULL)
   inc = laser->getIncrementChoiceDouble();
assert(inc > 0);
```

or maybe the other way around is better? (check Choice first).

I'm going to be testing some other ROS stuff on an LX, perhaps next week, but if you try this in the mean time let me know if it works.

Note there is also the pointcloud, this is actually the usual way of accessing laser data in ARIA.
