### ISSUE TITLE
Path Planning Goal Fail

### ISSUE THREAD

**Issue by robotsorcerer** [MobileRobots/ros-arnl#16]
Hi there, 

Thanks for this ROS interface to the arnl api.

I wrote a minimal msg publisher that sends the robot to specific points within a map in the robot's world.

I am sending the message to the topic `/rosarnl_node/goalname` using this [code]("/rosarnl_node/goalname") but I find that the robot hardly ever goes to specific goal points. I get errors similar to the following:

``` bash
[ WARN] [1466716747.907493619]: ARNL: PathPlanning: Goal Failed: -10240 -8655
[ INFO] [1466716748.003139016]: rosarnl_node: publishing new server status: Failed to get to Machining Table 2 (Robot lost)
[ INFO] [1466716767.724966229]: rosarnl_node: Received named goal "Lekan's Other Desk"
[ INFO] [1466716767.725162064]: rosarnl_node: ARNL path planning task state changed to NOT_INITIALIZED
[ INFO] [1466716767.725469924]: rosarnl_node: ARNL path planning task state changed to PLANNING_PATH
PathPlanning: Path Planning to Lekan's Other Desk
[ WARN] [1466716767.725718280]: ARNL: PathPlanning: Path Planning to Lekan's Other Desk
[ INFO] [1466716767.812567027]: rosarnl_node: publishing new server status: Going to Lekan's Other Desk
[ INFO] [1466716767.820123574]: rosarnl_node: ARNL path planning task state changed to MOVING_TO_GOAL
Localization lost (not initialized), failing
[ WARN] [1466716767.915438202]: ARNL: Localization lost (not initialized), failing
[ INFO] [1466716767.915556653]: rosarnl_node: ARNL path planning task state changed to FAILED_MOVE
PathPlanning: Goal Failed: -9346  -754
[ WARN] [1466716767.915994697]: ARNL: PathPlanning: Goal Failed: -9346  -754
[ INFO] [1466716768.011854367]: rosarnl_node: publishing new server status: Failed to get to Lekan's Other Desk (Robot lost)
[ INFO] [1466716787.725987027]: rosarnl_node: Received named goal "Teddy's Desk"
[ INFO] [1466716787.726180627]: rosarnl_node: ARNL path planning task state changed to NOT_INITIALIZED
[ INFO] [1466716787.726440436]: rosarnl_node: ARNL path planning task state changed to PLANNING_PATH
PathPlanning: Path Planning to Teddy's Desk
[ WARN] [1466716787.726712538]: ARNL: PathPlanning: Path Planning to Teddy's Desk
PathPlan: Cannot find main path (0 )
[ WARN] [1466716787.814196003]: ARNL: PathPlan: Cannot find main path (0 )
PathPlanning: PlanAndSetupAction: No path from -6560  3272     6 to Goal -6946  -483     0 
[ WARN] [1466716787.814323393]: ARNL: PathPlanning: PlanAndSetupAction: No path from -6560  3272     6 to Goal -6946  -483     0 
[ INFO] [1466716787.814397984]: rosarnl_node: ARNL path planning task state changed to FAILED_PLAN
PathPlanning: Goal Failed: -6946  -483
[ WARN] [1466716787.814565882]: ARNL: PathPlanning: Goal Failed: -6946  -483
[ INFO] [1466716787.820394556]: rosarnl_node: publishing new server status: Failed to get to Teddy's Desk (Cannot find path)
```

Attached are my screenshots. 
![goalfailed](https://cloud.githubusercontent.com/assets/8429860/16320628/c9550ad6-3966-11e6-88da-f4a2cdf42e83.png)

I would appreciate any help!

**Comment by reed-adept** [comment]
The most common reasons for ARNL to fail to get to a goal are:
- Localization is lost/uninitialized.  Navigation is specifically prevented in this case. Use localize to point in MobileEyes to reinitialize localization.
- Cannot find a path that allows the robot to pass through the map obstacle data, forbidden lines, forbidden zones, and sensor data. This is based on the size of the robot plus its clearance parameters, and also depends on the resolution of the planning grid (PlanRes parameter). Modify forbidden zones/lines, erase any obstacle data that are from temporary objects or people who are no longer there or artifacts on the very edges of walls/doorframes (but don't erase too much of the actual wall or doorway) or tiny points that did not get cleaned up by Mapper3.  You can also modify ARNL clearance parameters (in Path Planning section of Robot Configuration in MobileEyes).   The default PlanRes is normally fine but if you are trying to squeeze through an opening just barely big enough for the robot plus clearances then reducing it slightly might help.  Reducing PlanRes results in more computation load/time to plan and navigate the path especially in large maps.
- Some sensed obstacle or map object (forbidden line/area or map obstacle data) is on or near the goal point.
- Robot is on or very close to a forbidden line or zone or map data.  Manually move it away from the obstacle.

Check the status string, rosarnl_node log messages, and also the visualization of sensor data in MobileEyes to diagnose.

Is ARNL able to get to any of the other goals in the map?

I'll close this issue but if you think there is a bug regarding reporting robot status (such as lost) or similar, you can reopen with specifics of that.

**Comment by robotsorcerer** [comment]
Thanks @reed-adept !

**Comment by robotsorcerer** [comment]
Hey @reed-adept , I am trying to use the kinect 2 sensor to do the localization and navigation. But it seems the P3-DX does not support USB 3.0. Kinect only works on USB 3.0. Do you sell like breakout boards or usb 3.0s that we could buy? Thanks~!

**Comment by reed-adept** [comment]
Responded by separate email.  For bugs in ros-arnl, please open a new issue.  For other questions, email the users group or support@mobilerobots.com.
