### ISSUE TITLE
libAriaForArnl.so: undefined reference to `pthread`

### ISSUE THREAD

**Issue by robotsorcerer** [MobileRobots/ros-arnl#17]
I tried compiling the goalclient source code that ships with the deerhaps because libAriaForArnl is not in itself linked against that linux library. The error blob looks something like this:

``` bash
/usr/local/Arnl/lib/libAriaForArnl.so: undefined reference to `pthread_mutexattr_destroy'
/usr/local/Arnl/lib/libAriaForArnl.so: undefined reference to `pthread_create'
/usr/local/Arnl/lib/libAriaForArnl.so: undefined reference to `pthread_mutex_trylock'
/usr/local/Arnl/lib/libAriaForArnl.so: undefined reference to `pthread_sigmask'
/usr/local/Arnl/lib/libAriaForArnl.so: undefined reference to `pthread_mutexattr_settype'
/usr/local/Arnl/lib/libAriaForArnl.so: undefined reference to `pthread_join'
/usr/local/Arnl/lib/libAriaForArnl.so: undefined reference to `pthread_cancel'
/usr/local/Arnl/lib/libAriaForArnl.so: undefined reference to `pthread_detach'
/usr/local/Arnl/lib/libAriaForArnl.so: undefined reference to `pthread_mutexattr_init'

```

Here is my CMakeLists.txt: 
[CMakeLists.txt](https://github.com/MobileRobots/ros-arnl/files/376600/CMakeLists.txt) and my source code is basically the same as the goalclient's source code. Is there any thing I can do?

**Comment by reed-adept** [comment]
Are you using ros-arnl?   This github page is for bugs and issues specific to ros-arnl.  If not, please use the aria-users mailing list or email support@mobilerobots.com.  I'll respond separately. 

(the pthread functions are provided by libpthread, and I do see pthread in target_link_libraries in your CMakeLists.txt, so it should be linking to it.)
